version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - main: ./cmd/migrate
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm
    ldflags:
      - -s -w -X github.com/yodamad/migraptor/build.Version={{.Version}} -X github.com/yodamad/migraptor/build.Commit={{.Commit}} -X github.com/yodamad/migraptor/build.Date={{.Date}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: yodamad
    name: migraptor
  draft: false
  prerelease: auto
  make_latest: true
  replace_existing_draft: true
  name_template: '{{ .Tag }}'
  header: |

  footer: |
    ## Enjoy üçπ
    üìÜ {{ .Now.Format "2006-01-02" }} - Copyright @yodamad

brews:
  - name: migraptor
    homepage: https://github.com/yodamad/migraptor
    commit_author:
      name: yodamad
      email: mvincent.it@gmail.com
    license: Apache-2.0
    url_template: "https://github.com/yodamad/migraptor/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: yodamad
      name: homebrew-tools
      branch: main
