name: Release
run-name: Release ${{ github.event.inputs.tag }}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag name (starting with a `v`)'
        required: true

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-tag
        run: echo "Hello World!"